name: CI

on:
  push:
    branches:
      - main

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Validate HTML
      run: npm install -g html-validate && html-validate index.html

    - name: Validate JavaScript
      run: npm install -g eslint && eslint script.js

    - name: Install dependencies
      run: npm install

    - name: Run Jest tests
      run: npx jest
